### ISSUE TITLE
Class subkey of InprocServer32 uses the ProdId instead of the full namespace and class name

### ISSUE THREAD

**Issue by chadknudson** [NetOfficeFw/BuildTasks#12]
I ran into a situation where a team member was having issues with an AddIn not being loaded in Word, When I dug into it, the Class subkey has the ProdId and Word seems to use the full namespace and class name to instantiate the AddIn for loading it.

I wrote a small utility to auto generate a setup script for Inno Setup to create an installer for a NetOfficeFw AddIn. I stole profusely from your NetOfficeFw.BuildTasks to help ensure that I got all the registration correct.  I will publish this once I get through this current bug in our app.

**Comment by jozefizso** [comment]
Yes, for .NET COM types the ProgId must match the fully qualified class name.

**Comment by chadknudson** [comment]
I created a small app based heavily on your BuildTasks that will generate an INNO: Setup script file for creating an installer for a NetOfficeFw based COM AddIn for Microsoft Office. I have it up on my Github at https://github.com/chadknudson/INNOSetupScriptGeneratorForNetOfficeFW.  I will include it in my walkthrough series of documentation I'm working on for building NetOfficeFw addins. 

Thank you so much for all that you have done and continue to do on NetOfficeFw!!!
